FROM debian:11

RUN apt update
RUN apt install gcc make git opam libgmp-dev -y
RUN echo "Version $(opam --version)"

WORKDIR /usr/src
RUN git clone https://github.com/coq-community/chapar.git

WORKDIR /usr/src/chapar

# This one does not work.. since COQ is not installed
RUN make Makefile.coq