FROM debian:11

RUN apt update
RUN apt install make git opam libgmp-dev -y
RUN echo "Version $(opam --version)"

RUN opam init --disable-sandboxing
RUN opam repo add coq-released https://coq.inria.fr/opam/released
RUN opam install coq-chapar -y